name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7]

    steps:

    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install torch manually with CUDA
      run: |
        pip install torch==1.7.0+cu110 -f https://download.pytorch.org/whl/torch_stable.html
    - name: Install dependencies
      run: |
        pip install -r assets/requirement.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --exclude=__pycache__,.git,assets
    - name: Run tests
      run: |
        pip install pytest
        pytest -q

